openapi: 3.0.1
info:
  title: NHN Cloud Sender API facade
  description: This is a facade API for verifying the message senders through the NHN Cloud Notification service.
  version: v1.0.0
servers:
  - url: http://localhost:7071/api
paths:
  /senders:
    get:
      tags:
        - senders
      operationId: Senders.List
      parameters:
        - name: sendNo
          in: query
          description: Sender's phone number
          schema:
            type: string
        - name: useYn
          in: query
          description: Value indicating whether the number is used or not
          schema:
            type: string
        - name: blockYn
          in: query
          description: Value indicating whether the number is blocked or not
          schema:
            type: string
        - name: pageNum
          in: query
          description: Page number in the pagination. Default value is '1'
          schema:
            type: string
        - name: pageSize
          in: query
          description: Page size in the pagination. Default value is '15'
          schema:
            type: string
      responses:
        '200':
          description: The OK response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listSendersResponse'
              examples:
                sample:
                  summary: This represents the example entity for GetMessage response body.
                  value: '{"header":{"isSuccessful":true,"resultCode":0,"resultMessage":"SUCCESS"},"body":{"pageNum":1,"pageSize":15,"totalCount":2,"data":[{"serviceId":1234,"sendNo":"01012345678","useYn":"Y","blockYn":"N","blockReason":null,"createDate":"2020-01-01 00:00:00","createUser":"18ad9058-6466-48ef-8a78-08c27519ac24","updateDate":"2020-01-01 00:00:00","updateUser":"18ad9058-6466-48ef-8a78-08c27519ac24"},{"serviceId":5678,"sendNo":"01087654321","useYn":"Y","blockYn":"N","blockReason":null,"createDate":"2020-01-01 00:00:00","createUser":"18ad9058-6466-48ef-8a78-08c27519ac24","updateDate":"2020-01-01 00:00:00","updateUser":"18ad9058-6466-48ef-8a78-08c27519ac24"}]}}'
        '400':
          description: The input was invalid
        '500':
          description: The service has got an unexpected error
      security:
        - app_auth: [ ]
components:
  schemas:
    listSendersResponse:
      type: object
      properties:
        header:
          $ref: '#/components/schemas/responseHeaderModel'
        body:
          $ref: '#/components/schemas/responseCollectionBodyModel_listSendersResponseData'
    listSendersResponseData:
      type: object
      properties:
        serviceId:
          type: integer
          format: int32
        sendNo:
          type: string
        useYn:
          type: string
        blockYn:
          type: string
        blockReason:
          type: string
        createDate:
          type: string
        createUser:
          type: string
        updateDate:
          type: string
        updateUser:
          type: string
    responseCollectionBodyModel_listSendersResponseData:
      type: object
      properties:
        pageNum:
          type: integer
          format: int32
          nullable: true
        pageSize:
          type: integer
          format: int32
          nullable: true
        totalCount:
          type: integer
          format: int32
          nullable: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/listSendersResponseData'
    responseHeaderModel:
      type: object
      properties:
        isSuccessful:
          type: boolean
        resultCode:
          type: integer
          format: int32
        resultMessage:
          type: string
  securitySchemes:
    app_auth:
      type: http
      description: Toast API basic auth
      scheme: basic