name: Release to DockerHub

on:
  workflow_call:
    inputs:
      gh_tag:
        type: string
        required: true
      matrix_json:
        type: string
        required: true
        description: function app names in the format of JSON string array

jobs:
  deploy_docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fncapp-name: ${{ fromJson(inputs.matrix_json) }}

    steps:
    - name: Extract version from tag
      shell: pwsh
      run: |
        $version = (echo ${{ inputs.gh_tag }}) -replace "refs/tags/", ""

        echo "RELEASE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    - name: Download Function app artifacts
      uses: actions/download-artifact@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images to DockerHub
      shell: bash
      run: |
        cd ${{ matrix.fncapp-name }}

        curl https://raw.githubusercontent.com/${{ github.repository }}/main/src/nt-${{ matrix.fncapp-name }}/Dockerfile > Dockerfile
        curl https://raw.githubusercontent.com/${{ github.repository }}/main/src/nt-${{ matrix.fncapp-name }}/.dockerignore > .dockerignore
        curl https://raw.githubusercontent.com/${{ github.repository }}/main/src/nt-${{ matrix.fncapp-name }}/local.settings.sample.json > local.settings.json

        docker build . -t devrelkr/nt-${{ matrix.fncapp-name }}:latest -t devrelkr/nt-${{ matrix.fncapp-name }}:${{ env.RELEASE_VERSION }}
        docker push -a devrelkr/nt-${{ matrix.fncapp-name }}
