name: Make function-apps json

on:
  workflow_call:
    outputs:
     matrix_json:
      description: "function-apps with a format of JSON string array"
      value: ${{ jobs.make_fncapp_json.outputs.matrix_json }}
    

jobs:
  make_fncapp_json:
    runs-on: ubuntu-latest

    outputs:
      matrix_json: ${{ steps.make_json.outputs.fncapp_json }}

    steps:
    - name: Make function-apps JSON string array
      id: make_json
      shell: bash
      run: |
        # list of function-app names
        array_app_name=("sms" "sms-verify")

        JSON="["
        for i in ${!array_app_name[@]}; do
          if [ $i -eq 0 ]; then
            JSON=$JSON\"${array_app_name[$i]}\"
          else
            JSON=$JSON,\"${array_app_name[$i]}\"
          fi
        done
        JSON=$JSON]
        
        echo "::set-output name=fncapp_json::$JSON"