name: Make function-apps json

on:
  workflow_call:
    secrets:
      AZ_APP_SUFFIXES:
        required: true
    outputs:
     matrix_json:
      description: "function-apps with a format of JSON string array"
      value: ${{ jobs.make_fncapp_json.outputs.matrix_json }}

jobs:
  make_fncapp_json:
    runs-on: ubuntu-latest

    outputs:
      matrix_json: ${{ steps.make_json.outputs.fncapp_json }}

    steps:
    - name: Make function-apps JSON string array
      id: make_json
      shell: bash
      run: |
        string_fncapps="${{ secrets.AZ_APP_SUFFIXES }}"
        string_fncapps=$(echo $string_fncapps | tr "," " ")
        string_fncapps=$(echo $string_fncapps | tr " " "\n")

        JSON="["
        is_first=1
        for name in $string_fncapps; do
          if [ $is_first -eq 1 ]; then
            JSON=$JSON\'$name\'
            is_first=0
          else
            JSON=$JSON,\'$name\'
          fi
        done
        JSON=$JSON]
        
        echo "::set-output name=fncapp_json::$JSON"
        