name: Function Apps Matrix

on:
  workflow_call:
    outputs:
      matrix_json:
        description: function app names in the format of JSON string array
        value: ${{ jobs.make_matrix.outputs.matrix_json }}

jobs:
  make_matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix_json: ${{ steps.make_json.outputs.matrix_json }}

    steps:
    - name: Make Function apps JSON string array
      id: make_json
      shell: bash
      run: |
        string_fncapps="${{ secrets.AZURE_APP_SUFFIXES }}"
        string_fncapps=$(echo $string_fncapps | tr "," " ")
        string_fncapps=$(echo $string_fncapps | tr " " "\n")

        JSON="["
        is_first=1
        for name in $string_fncapps; do
          if [ $is_first -eq 1 ]; then
            JSON=$JSON\'$name\'
            is_first=0
          else
            JSON=$JSON,\'$name\'
          fi
        done
        JSON=$JSON]
        
        echo "::set-output name=matrix_json::$JSON"
