name: Release to Azure DEV

on:
  push:
    branches:
    - main
    - 'feature/*'
  
jobs:
  call_make_function_apps_matrix:
    uses: ./.github/workflows/make-function-apps-matrix.yaml
    secrets: 
      AZ_APP_SUFFIXES: ${{ secrets.AZURE_APP_SUFFIXES }}

  call_build_test_upload:
    uses: ./.github/workflows/build-test-upload.yaml
    needs: 
    - call_make_function_apps_matrix
    with:
      matrix_json: ${{ needs.call_make_function_apps_matrix.outputs.matrix_json }}
    secrets: 
      AZ_RESOURCE_NAME: ${{ secrets.AZURE_RESOURCE_NAME }}

  call_deployment_azure_dev:
    uses: ./.github/workflows/deployment-azure.yaml
    needs:
    - call_make_function_apps_matrix
    - call_build_test_upload
    with:
      gh_environment: DEV
      matrix_json: ${{ needs.call_make_function_apps_matrix.outputs.matrix_json }}
    secrets:
      AZ_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZ_RESOURCE_NAME: ${{ secrets.AZURE_RESOURCE_NAME }}
      AZ_ENVIRONMENT_CODE: ${{ secrets.AZURE_ENVIRONMENT_CODE_DEV }}
      AZ_LOCATION_CODE: ${{ secrets.AZURE_LOCATION_CODE }}
