name: Release to Azure DEV

on:
  push:
    branches:
    - main
    - 'feature/*'
  
jobs:
  call_make_function_apps_matrix:
    uses: ./.github/workflows/make-function-apps-matrix.yaml
    secrets: inherit

  call_build_test_upload:
    uses: ./.github/workflows/build-test-upload.yaml
    needs: 
    - call_make_function_apps_matrix
    with:
      matrix_json: ${{ needs.call_make_function_apps_matrix.outputs.matrix_json }}
    secrets: inherit

  call_deployment_azure_dev:
    uses: ./.github/workflows/deployment-azure.yaml
    needs:
    - call_make_function_apps_matrix
    - call_build_test_upload
    with:
      gh_environment: DEV
      matrix_json: ${{ needs.call_make_function_apps_matrix.outputs.matrix_json }}
    secrets: inherit
